version: "3.9"

volumes:
  db-data:
  redis_data:

services:
  sensor-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sensor_db
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - "5000:5000"

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sensor_db
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data





