basePath: /api
definitions:
  domain.ResponseDetectedFish:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: przmld033@gmail.com
  description: TEST API.
  title: SENSOR API
  version: "1.0"
paths:
  /api/v1/group/{groupName}/species:
    get:
      consumes:
      - application/json
      description: Retrieves the current detected fish species for a sensor group
        based on the provided group name.
      parameters:
      - description: Name of the sensor group
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.ResponseDetectedFish'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get current detected fish species for a sensor group
      tags:
      - sensors
  /api/v1/group/{groupName}/species/top/{top}:
    get:
      consumes:
      - application/json
      description: Retrieves the current top detected fish species for a sensor group
        based on the provided group name and other optional parameters.
      parameters:
      - description: Name of the sensor group
        in: path
        name: groupName
        required: true
        type: string
      - description: Number of top species to retrieve
        in: query
        name: top
        required: true
        type: integer
      - description: Start date for the period (UNIX timestamp)
        in: query
        name: from
        type: string
      - description: End date for the period (UNIX timestamp)
        in: query
        name: till
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.ResponseDetectedFish'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get current top detected fish species for a sensor group
      tags:
      - sensors
  /api/v1/group/{groupName}/temperature/average:
    get:
      consumes:
      - application/json
      description: Retrieves the temperature in Celsius for a sensor group based on
        the provided group name.
      parameters:
      - description: Name of the sensor group
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: temperature
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get temperature in Celsius for a sensor group
      tags:
      - sensors
  /api/v1/group/{groupName}/transparency/average:
    get:
      consumes:
      - application/json
      description: Retrieves the transparency percentage for a sensor group based
        on the provided group name.
      parameters:
      - description: Name of the sensor group
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: transparency
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get transparency percentage for a sensor group
      tags:
      - sensors
swagger: "2.0"
